### ISSUE TITLE
no way to set links with target="_blank"

### ISSUE THREAD

**Issue by Patrick-W-McMahon** [remarkjs/.github#2]
`[link](url){:target="_blank"}`

The parser doesn't add the target attribute to the A tag.

**Comment by wooorm** [comment]
Where what how why?

**Comment by Patrick-W-McMahon** [comment]
the specs for markdown shows that `[link](url){:target="_blank"} `would make an A tag with an attribute of target="_blank"

**Comment by wooorm** [comment]
Which spec?

No spec that I know of does that.

**Comment by Patrick-W-McMahon** [comment]
don't know how this was posted in remarkjs/.github should be in remarkjs/react-markdown
